### ISSUE TITLE
too many redirects

### ISSUE THREAD

**Issue by wendyck** [wendyck/dumb-python-stuff#3]
www.oneok.com/security
    \* too many redirects, kills even requests lib

**Comment by wendyck** [comment]
See also 
www.arrow.com/security
(closed https one too fast?)

Traceback (most recent call last):
  File "./security-url-check-2.py", line 19, in <module>
    checkURL(line);
  File "./security-url-check-2.py", line 8, in checkURL
    r = requests.get(companyurl)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, *_kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, *_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, *_send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 597, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 195, in resolve_redirects
    *_adapter_kwargs
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 433, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
